[build-system]
requires = [
    "setuptools",
    "oldest-supported-numpy ; python_version<'3.12'",
    "numpy; python_version>='3.12'",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "pytest --import-mode=importlib {project}/mahotas/tests"
test-extras = ["tests"]
skip = ["*manylinux*i686", "pp38-macosx_arm64", "pp37*"]
environment = { PIP_PREFER_BINARY="1", PIP_VERBOSE="1" }